<script lang="ts">
  // Forms
  import { enhance } from '$app/forms';
  // Components
  import { BaseButton, BaseModal, PageHeader } from '$lib/components';
  import { RecordTileList } from '$lib/components/collection';
  import { Alert, Loader, NumberInput, SubmitButton, TextInput } from '$lib/components/forms';
  // Interfaces
  import type { IRecordErrors } from '$lib/schema/validationSchema';
  import type { IRecords, IUpdateRecords, IUserRecord } from '$lib/types.js';
  // Icons
  import AddIcon from '~icons/mdi/add';

  /**
   * @description Record data
   */
  export let data;

  let { userRecordsData } = data;

  let recordListData = userRecordsData as IRecords[];

  /**
   * @description User's prompt for OpenAI
   */
  let userPrompt = '';

  /**
   * @description Modal state
   */
  let showAddRecordModal = false;

  const BLANK_RECORD: IUserRecord = {
    title: '',
    artist: '',
    year: '',
    genre: ''
  };

  /**
   * @description Record object - initially generated by OpenAI
   */
  let userRecord: IUserRecord = BLANK_RECORD;

  /**
   * @description Form data
   */
  export let form;

  /**
   * @description Form errors
   */
  let formErrors: IRecordErrors | undefined;

  // Individual form errors
  let titleErrors: string | undefined;
  let artistErrors: string | undefined;
  let yearErrors: string | undefined;
  let genreErrors: string | undefined;

  function clearFormErrors() {
    if (form && 'errors' in form) {
      form.errors = undefined;
      formErrors = undefined;
      titleErrors = undefined;
      artistErrors = undefined;
      yearErrors = undefined;
      genreErrors = undefined;
    }
  }

  function openAddRecordModal(state: boolean) {
    showAddRecordModal = state;
    userRecord = structuredClone(BLANK_RECORD);
    clearFormErrors();
  }

  /**
   * @description Loading state
   */
  let loading = false;

  function setLoadingState(state: boolean) {
    loading = state;
  }

  // Form Handler
  $: if (form) {
    // Success Handling
    if (form.success) {
      setLoadingState(false);

      // Populate record data from OpenAI in add record modal
      if ('generatedRecord' in form && form.generatedRecord) {
        userRecord = form.generatedRecord as IUserRecord;
        form.generatedRecord = undefined;
        showAddRecordModal = true;
      }

      // Update record list after adding/updating/deleting record
      if ('createdRecord' in form && form.createdRecord) {
        const createdRecord = form.createdRecord as IRecords;
        recordListData = [...recordListData, createdRecord];
        form.createdRecord = undefined;
      }

      if ('updatedRecord' in form && form.updatedRecord) {
        const updatedRecord = form.updatedRecord as IUpdateRecords;
        recordListData = recordListData.map((record) => {
          if (updatedRecord.id && record.id === updatedRecord.id) {
            const { title, artist, year, genre } = updatedRecord;
            if (title) {
              record.title = title;
            }
            if (artist) {
              record.artist = artist;
            }
            if (year || year === null) {
              record.year = year;
            }
            if (genre || genre === null) {
              record.genre = genre;
            }
          }
          return record;
        });
        form.updatedRecord = undefined;
      }

      if ('deletedRecordId' in form && form.deletedRecordId) {
        const deletedRecordId = form.deletedRecordId as string;
        recordListData = recordListData.filter((record) => record.id !== deletedRecordId);
        form.deletedRecordId = undefined;
      }

      clearFormErrors();
    } else {
      // Error Handling
      if ('errors' in form && form.errors) {
        setLoadingState(false);
        formErrors = form.errors as IRecordErrors;
        titleErrors = formErrors.title;
        artistErrors = formErrors.artist;
        yearErrors = formErrors.year;
        genreErrors = formErrors.genre;
        form.errors = undefined;
      }
    }
  }
</script>

<svelte:head>
  <title>Your Collection</title>
  <meta name="description" content="Music Vault - Collection" />
</svelte:head>

{#if loading}
  <Loader bind:loading />
{/if}

<div>
  <PageHeader title="Collection" />

  {#if form && form.message.length > 0}
    <Alert
      time={5000}
      message={form.message}
      onDestroyCallback={() => {
        if (form) {
          form.message = '';
        }
        userPrompt = '';
      }}
    />
  {/if}

  <form
    method="POST"
    action="?/generateRecord"
    class="flex items-end"
    use:enhance={() => {
      return async ({ result, update }) => {
        update();
        if (result.type === 'success') {
          openAddRecordModal(false);
        }
      };
    }}
  >
    <TextInput
      required
      name="add_record"
      label="Search for Record (Powered by OpenAI)"
      placeholder="Al Green - Greatest Hits"
      bind:value={userPrompt}
    />

    <div class="ml-4">
      <SubmitButton text="Generate" onClick={() => setLoadingState(true)} />
    </div>
  </form>

  <div class="mt-4 flex items-center justify-between">
    <h3>Current Collection:</h3>
    <BaseButton text="Add Record" onClick={() => openAddRecordModal(true)}>
      <AddIcon />
    </BaseButton>
  </div>

  {#if recordListData && recordListData.length > 0}
    <RecordTileList
      setLoadingCallback={() => setLoadingState(true)}
      {recordListData}
      {clearFormErrors}
      bind:formErrors
    />
  {:else}
    <p>No records logged yet, try adding one!</p>
  {/if}
</div>

<!-- Add Record Modal -->
{#if showAddRecordModal}
  <form
    method="POST"
    action="?/createRecord"
    use:enhance={() => {
      return async ({ result, update }) => {
        update();
        if (result.type === 'success') {
          openAddRecordModal(false);
          userRecord = structuredClone(BLANK_RECORD);
        }
      };
    }}
  >
    <BaseModal
      closeText="Cancel"
      onCancelCallback={() => openAddRecordModal(false)}
      bind:showModal={showAddRecordModal}
    >
      <h3 slot="header">Add record</h3>

      <div slot="content">
        <TextInput
          required
          name="title"
          label="Title"
          placeholder="Record Title"
          bind:value={userRecord.title}
          bind:inputError={titleErrors}
        />

        <TextInput
          required
          name="artist"
          label="Artist"
          placeholder="Record Artist"
          bind:value={userRecord.artist}
          bind:inputError={artistErrors}
        />

        <NumberInput
          name="year"
          label="Year"
          placeholder="Record Year"
          bind:value={userRecord.year}
          bind:inputError={yearErrors}
        />

        <TextInput
          name="genre"
          label="Genre"
          placeholder="Record Genre"
          bind:value={userRecord.genre}
          bind:inputError={genreErrors}
        />
      </div>

      <div slot="footer">
        <SubmitButton text="Add" onClick={() => setLoadingState(true)} />
      </div>
    </BaseModal>
  </form>
{/if}
